version: 2.1

commands:
  checkout_with_workspace:
    steps:
      - checkout
      - attach_workspace:
          at: ~/

jobs:
  release_github:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout_with_workspace
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: Install rsync
          command: sudo apt install rsync
      - run:
          name: Release new version on Github
          command: npm run release
      # Persist assets generated for the GH release, so that they are available for WPORG release.
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  release_wporg:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout_with_workspace
      - run:
          name: Release new version on WordPress.org
          command: ./node_modules/newspack-scripts//release-wporg.sh

  post_release:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout_with_workspace
      - run:
          name: Perform post-release chores
          command: ./node_modules/newspack-scripts/post-release.sh

workflows:
  version: 2
  main:
    jobs:
      - release_github:
          filters:
            branches:
              only:
                - release
                - alpha
                - /^hotfix\/.*/
      - post_release:
          requires:
            - release_github
          filters:
            branches:
              only:
                - release
      - release_wporg:
          requires:
            - release_github
          filters:
            branches:
              only:
                - release
